---
- name: "Laboratorio de Registros"
  hosts: nodos
  tasks:
    - name: "Consultar hora actual"
      command: "date +%T"
      register: hora_actual

    - name: "Cambiar la zona horaria"
      timezone:
        name: "Europe/Moscow"
      register: cambio_zona_horaria
    
    - name: "Fichero de datos horarios"
      file:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}"
        state: touch

    - name: "Consultar nueva hora"
      command: "date +%T"
      register: hora_nueva
    
    - name: "Registrar horas"
      lineinfile:
        path: "/tmp/datos_horarios_{{ ansible_facts['hostname'] }}"
        line: |
          La zona horaria antes del cambio era {{ cambio_zona_horaria.diff.before.name }} y la hora era {{ hora_actual }}
          La zona horaria despues del cambio es {{ cambio_zona_horaria.diff.before.name }} y la hora es {{ hora_nueva }}
    
    - name: "Vuelta atras"
      timezone:
        name: {{ cambio_zona_horaria.diff.before.name }} 
...